### ISSUE TITLE
docker build fails *FATAL*

### ISSUE THREAD

**Issue by rcemper** [banksiaglobal/femtech-reminder#1]
C:\GitHub\femtech-reminder>docker compose up iris -d
[+] Running 0/1
 - iris Error
Error response from daemon: pull access denied for intersystems/iris
 repository does not exist or may require 'docker login': 
 denied: requested access to the resource is denied

**Comment by k-otto-k** [comment]
works in branch MAIN, failed in MASTER

**Comment by rcemper** [comment]
ok

**Comment by rcemper** [comment]
ok in MAIIN
